# Corrected render.yaml (Version 3)

# Top-level definition for all persistent disks in this Blueprint
disks:
  - name: data-disk
    mountPath: /data # The path where the disk will be available
    sizeGB: 1

# Definition for all services
services:
  # The Flask Web Application
  - type: web
    name: kenshi-shop
    env: python
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    disk:
      name: data-disk 
      mountPath: /data
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false 
      - key: TELEGRAM_BOT_TOKEN
        sync: false 
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false 
      - key: DATA_FOLDER_PATH
        value: /data

  # The Telegram Bot Background Worker
  - type: worker
    name: kenshi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'from app import load_data, run_bot; load_data(); run_bot()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false  - type: worker
    name: kenshi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'from app import load_data, run_bot; load_data(); run_bot()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false
