services:
  # The Flask Web Application
  - type: web
    name: kenshi-shop
    env: python
    plan: free # Use the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6 # Specify a Python version
      - key: SECRET_KEY
        generateValue: true # Let Render generate a random secret key
      - key: ADMIN_PASSWORD
        sync: false # Set this in the Render Dashboard
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Set this in the Render Dashboard
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false # Set this in the Render Dashboard
      - key: DATA_FOLDER_PATH
        value: /data # The mount path for our persistent disk
    
    # Persistent Disk for storing JSON files and uploads
    disks:
      - name: data-disk
        mountPath: /data
        sizeGB: 1

  # The Telegram Bot Background Worker
  - type: worker
    name: kenshi-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'from app import load_data, run_bot; load_data(); run_bot()'" # Command to start only the bot
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_CHAT_ID
        sync: false