services:
  # The Flask Web Application
  - type: web
    name: kenshi-shop-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - fromGroup: kenshi-shop-secrets

  # The Telegram Bot Listener
  - type: worker
    name: kenshi-shop-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_worker.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - fromGroup: kenshi-shop-secrets

# Define the environment variable group for secrets
envVarGroups:
  - name: kenshi-shop-secrets
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DETA_PROJECT_KEY # <-- NEW AND MOST IMPORTANT
        value: "Your_Deta_Project_Key_Here"
      - key: ADMIN_PASSWORD
        value: "Your_Admin_Password_Here"
      - key: TELEGRAM_BOT_TOKEN
        value: "Your_Telegram_Token_Here"
      - key: ADMIN_TELEGRAM_CHAT_ID
        value: "Your_Admin_Chat_ID_Here"